<template>
  <UModal
    v-model:open="open"
    :title="$t('templates.createTemplate')"
    :description="$t('templates.modal.addDescription')"
  >
    <UButton
      :label="$t('templates.addNew')"
      icon="i-lucide-plus"
    />

    <template #body>
      <TemplateForm
        ref="formRef"
        :submit-label="$t('common.create')"
        :is-submitting="isSubmitting"
        @submit="onSubmit"
        @cancel="open = false"
      />
    </template>
  </UModal>
</template>

<script setup lang="ts">
import type { LessonTemplate } from '~/types/session'

const { t } = useI18n()
const open = ref(false)
const formRef = ref()
const toast = useToast()
const isSubmitting = ref(false)

type TemplateFormData = Omit<LessonTemplate, 'id' | 'instructorIds' | 'instructorNames'>

async function onSubmit(data: TemplateFormData) {
  isSubmitting.value = true
  try {
    // TODO: Implement actual API call to create template
    // The template will also need:
    // - id (generated by backend)
    // - instructorIds: []
    // - instructorNames: []

    toast.add({
      title: t('templates.modal.successTitle'),
      description: t('templates.modal.successDescription', { name: data.name }),
      color: 'success'
    })

    open.value = false
    formRef.value?.reset()
  } catch (error) {
    toast.add({
      title: t('common.error'),
      description: t('templates.modal.errorDescription'),
      color: 'error'
    })
  } finally {
    isSubmitting.value = false
  }
}
</script>
