export default defineEventHandler(() => {
  return [
    {
      id: 'tpl-1',
      name: 'Beginner Surf Lesson',
      serviceType: 'surf_lesson',
      level: 'beginner',
      defaultDuration: 90,
      defaultTimeWindow: 'morning',
      minGroupSize: 1,
      maxGroupSize: 6,
      defaultLocation: 'Canggu Beach',
      instructorIds: ['inst-1', 'inst-3'],
      instructorNames: ['Made Surya', 'Ketut Dharma'],
      price: 50,
      currency: 'EUR',
      description: 'Perfect for first-time surfers. Learn the basics in a safe environment.',
      isActive: true,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z'
    },
    {
      id: 'tpl-2',
      name: 'Intermediate Surf Coaching',
      serviceType: 'surf_coaching',
      level: 'intermediate',
      defaultDuration: 120,
      defaultTimeWindow: 'morning',
      minGroupSize: 1,
      maxGroupSize: 4,
      defaultLocation: 'Uluwatu',
      instructorIds: ['inst-1', 'inst-2'],
      instructorNames: ['Made Surya', 'Wayan Agung'],
      price: 80,
      currency: 'EUR',
      description: 'Improve your technique and wave selection with personalized coaching.',
      isActive: true,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z'
    },
    {
      id: 'tpl-3',
      name: 'Advanced Surf Guiding',
      serviceType: 'surf_guiding',
      level: 'advanced',
      defaultDuration: 180,
      defaultTimeWindow: 'morning',
      minGroupSize: 2,
      maxGroupSize: 4,
      defaultLocation: 'Padang Padang',
      instructorIds: ['inst-2'],
      instructorNames: ['Wayan Agung'],
      price: 120,
      currency: 'EUR',
      description: 'Explore the best surf spots with an experienced local guide.',
      isActive: true,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z'
    },
    {
      id: 'tpl-4',
      name: 'Afternoon Beginner Lesson',
      serviceType: 'surf_lesson',
      level: 'beginner',
      defaultDuration: 90,
      defaultTimeWindow: 'afternoon',
      minGroupSize: 1,
      maxGroupSize: 6,
      defaultLocation: 'Seminyak Beach',
      instructorIds: ['inst-3'],
      instructorNames: ['Ketut Dharma'],
      price: 45,
      currency: 'EUR',
      description: 'Afternoon session for beginners, perfect for those who prefer later start times.',
      isActive: true,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z'
    }
  ]
})
