<template>
  <UModal
    v-model:open="open"
    :title="$t('businesses.modal.addTitle')"
    :description="$t('businesses.modal.addDescription')"
  >
    <UButton
      :label="$t('businesses.addNew')"
      icon="i-lucide-plus"
    />

    <template #body>
      <UForm
        :schema="schema"
        :state="state"
        class="space-y-4"
        @submit="onSubmit"
      >
        <UFormField
          :label="$t('businesses.form.name')"
          name="name"
        >
          <UInput
            v-model="state.name"
            :placeholder="$t('businesses.form.namePlaceholder')"
            class="w-full"
          />
        </UFormField>

        <UFormField
          :label="$t('businesses.form.type')"
          name="type"
        >
          <USelectMenu
            v-model="state.type"
            :items="businessTypeOptions"
            :placeholder="$t('businesses.form.typePlaceholder')"
            value-key="value"
          />
        </UFormField>

        <UFormField
          :label="$t('businesses.form.address')"
          name="address"
        >
          <UInput
            v-model="state.address"
            :placeholder="$t('businesses.form.addressPlaceholder')"
            class="w-full"
          />
        </UFormField>

        <div class="grid grid-cols-2 gap-4">
          <UFormField
            :label="$t('businesses.form.latitude')"
            name="lat"
          >
            <UInput
              v-model.number="state.lat"
              :placeholder="$t('businesses.form.latitudePlaceholder')"
              type="number"
              step="any"
              class="w-full"
            />
          </UFormField>
          <UFormField
            :label="$t('businesses.form.longitude')"
            name="lng"
          >
            <UInput
              v-model.number="state.lng"
              :placeholder="$t('businesses.form.longitudePlaceholder')"
              type="number"
              step="any"
              class="w-full"
            />
          </UFormField>
        </div>

        <UFormField
          :label="$t('businesses.form.image')"
          name="image"
        >
          <UInput
            v-model="state.image"
            :placeholder="$t('businesses.form.imagePlaceholder')"
            class="w-full"
          />
        </UFormField>

        <UFormField
          :label="$t('businesses.form.description')"
          name="description"
        >
          <UTextarea
            v-model="state.description"
            :placeholder="$t('businesses.form.descriptionPlaceholder')"
            class="w-full"
            :rows="4"
          />
        </UFormField>

        <div class="flex items-center gap-2">
          <UCheckbox v-model="state.isActive" />
          <label class="text-sm font-medium text-gray-700 dark:text-gray-300">
            {{ $t('common.active') }}
          </label>
        </div>

        <div class="flex justify-end gap-2 pt-4">
          <UButton
            :label="$t('common.cancel')"
            color="neutral"
            variant="subtle"
            @click="open = false"
          />
          <UButton
            :label="$t('businesses.modal.createButton')"
            color="primary"
            variant="solid"
            type="submit"
          />
        </div>
      </UForm>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import * as z from 'zod'
import type { FormSubmitEvent } from '@nuxt/ui'
import { SurfBusinessType } from '~/types/business'

const { t } = useI18n()

const schema = z.object({
  name: z.string().min(2, t('businesses.validation.nameMinLength')),
  address: z.string().min(5, t('businesses.validation.addressMinLength')),
  type: z.enum(SurfBusinessType),
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  image: z.string().url(t('businesses.validation.imageUrl')),
  description: z.string().min(10, t('businesses.validation.descriptionMinLength')),
  isActive: z.boolean().optional().default(true)
})

const open = ref(false)

type Schema = z.output<typeof schema>

const businessTypeOptions = Object.values(SurfBusinessType).map(type => ({
  label: type,
  value: type
}))

const state = reactive<Partial<Schema>>({
  name: undefined,
  address: undefined,
  type: undefined,
  lat: undefined,
  lng: undefined,
  image: undefined,
  description: undefined,
  isActive: true
})

const toast = useToast()
async function onSubmit(event: FormSubmitEvent<Schema>) {
  // TODO: Implement actual API call to create business
  // The business will also need:
  // - id (generated by backend)
  // - latLng: { lat: event.data.lat, lng: event.data.lng }
  // - aggregatedRating: { rating: 0, reviewCount: 0 }
  // - isApproved: false (default for new businesses)

  toast.add({
    title: t('businesses.modal.successTitle'),
    description: t('businesses.modal.successDescription', { name: event.data.name }),
    color: 'success'
  })
  open.value = false

  // Reset form
  Object.assign(state, {
    name: undefined,
    address: undefined,
    type: undefined,
    lat: undefined,
    lng: undefined,
    image: undefined,
    description: undefined,
    isActive: true
  })
}
</script>
