import type { SurfBoard } from '~/types/surfboard'
import { BoardType, BoardCondition } from '~/types/surfboard'

// Helper function to generate random IDs
const generateId = () => Math.random().toString(36).substr(2, 9)

// Helper function to generate random ratings
const generateRating = () => ({
  rating: Math.round((Math.random() * 1.5 + 3.5) * 10) / 10,
  reviewCount: Math.floor(Math.random() * 150) + 10
})

// Mock surfboards for rental activities
const mockSurfboards: SurfBoard[] = [
  {
    id: generateId(),
    name: 'Beginner Longboard',
    type: BoardType.LONGBOARD,
    brand: 'Catch Surf',
    model: 'Beater',
    length: 9.0,
    width: 23,
    thickness: 3.5,
    volume: 75,
    condition: BoardCondition.EXCELLENT,
    description:
      'Perfect for beginners with soft construction and easy paddling',
    images: ['/images/surfboards/longboard-1.jpg'],
    pricePerHour: 8,
    pricePerDay: 25,
    pricePerWeek: 150,
    isAvailable: true,
    features: ['Soft construction', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Performance Shortboard',
    type: BoardType.SHORTBOARD,
    brand: 'Firewire',
    model: 'Dominator',
    length: 6.2,
    width: 19.5,
    thickness: 2.25,
    volume: 32,
    condition: BoardCondition.GOOD,
    description: 'High-performance shortboard for advanced surfers',
    images: ['/images/surfboards/shortboard-1.jpg'],
    pricePerHour: 12,
    pricePerDay: 40,
    pricePerWeek: 200,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Professional wax'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Funboard All-Rounder',
    type: BoardType.FUNBOARD,
    brand: 'Channel Islands',
    model: 'Average Joe',
    length: 7.6,
    width: 22,
    thickness: 2.75,
    volume: 48,
    condition: BoardCondition.EXCELLENT,
    description: 'Versatile board perfect for intermediate surfers',
    images: ['/images/surfboards/funboard-1.jpg'],
    pricePerHour: 10,
    pricePerDay: 35,
    pricePerWeek: 180,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Fish Board',
    type: BoardType.FISH,
    brand: 'Lost',
    model: 'RNF Retro',
    length: 5.8,
    width: 20.5,
    thickness: 2.5,
    volume: 35,
    condition: BoardCondition.GOOD,
    description: 'Retro fish design for small wave performance',
    images: ['/images/surfboards/fish-1.jpg'],
    pricePerHour: 11,
    pricePerDay: 38,
    pricePerWeek: 190,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Mini Mal',
    type: BoardType.MINI_MAL,
    brand: 'JS Industries',
    model: 'Monsta Box',
    length: 8.0,
    width: 22.5,
    thickness: 3.0,
    volume: 55,
    condition: BoardCondition.FAIR,
    description: 'Stable mini malibu for learning and small waves',
    images: ['/images/surfboards/minimal-1.jpg'],
    pricePerHour: 9,
    pricePerDay: 30,
    pricePerWeek: 160,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Big Wave Gun',
    type: BoardType.GUN,
    brand: 'Pyzel',
    model: 'The Shadow',
    length: 7.6,
    width: 19,
    thickness: 2.75,
    volume: 38,
    condition: BoardCondition.EXCELLENT,
    description: 'Specialized gun for tackling big waves',
    images: ['/images/surfboards/gun-1.jpg'],
    pricePerHour: 15,
    pricePerDay: 50,
    pricePerWeek: 250,
    isAvailable: true,
    features: ['Future fins', 'Leash included', 'Professional wax'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Soft Top Foam Board',
    type: BoardType.SOFTBOARD,
    brand: 'Wavestorm',
    model: 'Classic',
    length: 8.0,
    width: 23,
    thickness: 3.25,
    volume: 70,
    condition: BoardCondition.EXCELLENT,
    description: 'Perfect beginner board with soft foam construction',
    images: ['/images/surfboards/softboard-1.jpg'],
    pricePerHour: 7,
    pricePerDay: 20,
    pricePerWeek: 120,
    isAvailable: true,
    features: ['Soft construction', 'Leash included', 'No wax needed'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Performance Fish',
    type: BoardType.FISH,
    brand: 'Haydenshapes',
    model: 'Hypto Krypto',
    length: 5.6,
    width: 21,
    thickness: 2.5,
    volume: 30,
    condition: BoardCondition.EXCELLENT,
    description: 'Modern performance fish for critical surfing',
    images: ['/images/surfboards/fish-2.jpg'],
    pricePerHour: 13,
    pricePerDay: 45,
    pricePerWeek: 220,
    isAvailable: false,
    features: ['FCS fins', 'Leash included', 'Professional wax'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Classic Longboard',
    type: BoardType.LONGBOARD,
    brand: 'Bing Surfboards',
    model: 'Collector',
    length: 9.6,
    width: 23.5,
    thickness: 3.0,
    volume: 80,
    condition: BoardCondition.GOOD,
    description: 'Traditional longboard for classic noseriding',
    images: ['/images/surfboards/longboard-2.jpg'],
    pricePerHour: 10,
    pricePerDay: 35,
    pricePerWeek: 180,
    isAvailable: true,
    features: ['Single fin setup', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Grom Shortboard',
    type: BoardType.SHORTBOARD,
    brand: 'DHD',
    model: 'Mini Twin',
    length: 5.4,
    width: 18.5,
    thickness: 2.125,
    volume: 26,
    condition: BoardCondition.EXCELLENT,
    description: 'Perfect shortboard for smaller surfers and groms',
    images: ['/images/surfboards/shortboard-2.jpg'],
    pricePerHour: 10,
    pricePerDay: 32,
    pricePerWeek: 160,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Professional wax'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Mid-Length Cruiser',
    type: BoardType.FUNBOARD,
    brand: 'Album Surfboards',
    model: 'Disc',
    length: 7.2,
    width: 22,
    thickness: 2.875,
    volume: 50,
    condition: BoardCondition.EXCELLENT,
    description: 'Modern mid-length for easy wave catching',
    images: ['/images/surfboards/funboard-2.jpg'],
    pricePerHour: 11,
    pricePerDay: 38,
    pricePerWeek: 190,
    isAvailable: true,
    features: ['FCS fins', 'Leash included', 'Wax applied'],
    rating: generateRating()
  },
  {
    id: generateId(),
    name: 'Step-Up Board',
    type: BoardType.GUN,
    brand: 'Sharp Eye',
    model: 'Storm Blade',
    length: 6.8,
    width: 19.25,
    thickness: 2.5,
    volume: 35,
    condition: BoardCondition.GOOD,
    description: 'Step-up for bigger days and hollow waves',
    images: ['/images/surfboards/gun-2.jpg'],
    pricePerHour: 14,
    pricePerDay: 48,
    pricePerWeek: 240,
    isAvailable: true,
    features: ['Future fins', 'Leash included', 'Professional wax'],
    rating: generateRating()
  }
]

export default defineEventHandler(() => {
  return {
    surfboards: mockSurfboards,
    total: mockSurfboards.length
  }
})

