<template>
  <UModal
    v-model:open="open"
    :title="$t('surfboards.modal.addTitle')"
    :description="$t('surfboards.modal.addDescription')"
  >
    <UButton
      :label="$t('surfboards.addNew')"
      icon="i-lucide-plus"
    />

    <template #body>
      <SurfboardForm
        ref="formRef"
        :submit-label="$t('surfboards.modal.createButton')"
        @submit="onSubmit"
        @cancel="open = false"
      />
    </template>
  </UModal>
</template>

<script setup lang="ts">
import type { SurfBoard } from '~/types/surfboard'

const { t } = useI18n()
const open = ref(false)
const formRef = ref()
const toast = useToast()

type SurfboardFormData = Omit<SurfBoard, 'id' | 'images' | 'rating'>

async function onSubmit(data: SurfboardFormData) {
  // TODO: Implement actual API call to create surfboard
  // The surfboard will also need:
  // - id (generated by backend)
  // - images: [data.image]
  // - features: [] (can be added later)

  toast.add({
    title: t('surfboards.modal.successTitle'),
    description: t('surfboards.modal.successDescription', { name: data.name }),
    color: 'success'
  })
  open.value = false

  // Reset form
  formRef.value?.reset()
}
</script>
