<template>
  <UModal
    v-model:open="open"
    :title="$t('sessions.modal.addTitle')"
    :description="$t('sessions.modal.addDescription')"
  >
    <UButton
      :label="$t('sessions.createSession')"
      icon="i-heroicons-plus"
    />

    <template #body>
      <SessionForm
        ref="formRef"
        :submit-label="$t('sessions.modal.createButton')"
        @submit="onSubmit"
        @cancel="open = false"
      />
    </template>
  </UModal>
</template>

<script setup lang="ts">
import type { Session } from '~/types/session'

const { t } = useI18n()
const open = ref(false)
const formRef = ref()
const toast = useToast()

type SessionFormData = Omit<Session, 'id' | 'createdAt' | 'updatedAt'>

async function onSubmit(data: SessionFormData) {
  // TODO: Implement actual API call to create session
  // The session will also need:
  // - id (generated by backend)
  // - createdAt (generated by backend)
  // - updatedAt (generated by backend)

  toast.add({
    title: t('sessions.modal.successTitle'),
    description: t('sessions.modal.successDescription', { name: data.serviceName }),
    color: 'success'
  })
  open.value = false

  // Reset form
  formRef.value?.reset()
}
</script>
